server.port=8081
spring.application.name=reservation

# MySQL (XAMPP)
spring.datasource.url=jdbc:mysql://localhost:3306/rezervo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# JWT
jwt.secret=bu_cok_uzun_ve_gizli_bir_secret_key_en_az_32_karakter_olmali_1234